/* Regression contract for the restored normalized database. Former global-function tests
 * referenced removed code and failed 10/10 at baseline ca2fe2a. Test public behavior instead. */
const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../assets/js/core'),localities=require('../assets/localidades_dta_cr.json'),cantons=require('../assets/cantones_logistica_cr.json'),officialHomonyms=require('../docs/homonimos_oficiales_cr.json');
const homonyms=Object.fromEntries(officialHomonyms.map(item=>[item.norm,item.ubicaciones.map(place=>[place.canton,place.provincia])]));
test('exact destination precedes partial matches and never matches company name',()=>{
 const rows=[{id:'A',nombre:'MATINA EXPRESS',destinos:['LIBERIA']},{id:'B',nombre:'TOROS',destinos:['MATINA']},{id:'C',nombre:'OTRA',destinos:['MATINA CENTRO']}];
 assert.deepEqual(C.search(rows,'destino',' matína ').map(t=>t.id),['B']);assert.deepEqual(C.search(rows,'transportista','toros').map(t=>t.id),['B']);assert.deepEqual(C.search(rows,'destino',''),[]);
});
test('marker count is unique companies, not warehouse count',()=>{assert.equal(C.operatorCount([{carrierId:'A'},{carrierId:'A'},{carrierId:'B'}]),2);});
test('Haversine meters and invalid coordinate navigation',()=>{assert.ok(Math.abs(C.distance({lat:10,lng:-84},{lat:10.001,lng:-84})-0.111195)<0.00001);for(const lat of [null,'10',NaN,Infinity,0])assert.equal(C.validGPS({lat,lng:-84}),false);});
test('global proximity uses each carrier nearest warehouse and puts that warehouse first',()=>{const here={lat:10,lng:-84},rows=[{id:'A',bodegas:[{id:'far',lat:10.1,lng:-84},{id:'near',lat:10.001,lng:-84}]},{id:'B',bodegas:[{id:'middle',lat:10.01,lng:-84}]}];assert.deepEqual(C.sortByNearest(rows,here).map(t=>t.id),['A','B']);assert.deepEqual(C.warehouseOrder(rows[0],here).map(x=>x.b.id),['near','far']);});
test('split schedules distinguish open, lunch and closed',()=>{const t={horario:'',LV_Apertura_1:'08:00',LV_Cierre_1:'12:00',LV_Apertura_2:'13:00',LV_Cierre_2:'17:00',SAB_Apertura_1:'08:00',SAB_Cierre_1:'12:00'};assert.equal(C.scheduleStatusAt(t,1,9*60).state,'open');assert.equal(C.scheduleStatusAt(t,1,12*60+30).state,'lunch');assert.equal(C.scheduleStatusAt(t,1,18*60).state,'closed');assert.match(C.scheduleStatusAt(t,1,12*60+30).detail,/13:00/);});
test('legacy hours remain usable while structured AppSheet slots are introduced',()=>{assert.deepEqual(C.scheduleSlots({horario:'L-V 08:00 12:00 13:00 17:00 S 08:00 12:00'}),{lv:[{open:480,close:720},{open:780,close:1020}],sab:[{open:480,close:720}]});assert.equal(C.scheduleStatusAt({horario:'NO ESPECIFICADO'},1,600).state,'unknown');});
test('Spanish display capitalization keeps internal connectors lowercase',()=>{assert.equal(C.displayName('CARGAS Y ENCOMIENDAS DEL PACIFICO'),'Cargas y Encomiendas del Pacifico');assert.equal(C.displayName('EL COCO'),'El Coco');assert.equal(C.displayName('LAS JUNTAS DE ABANGARES'),'Las Juntas de Abangares');});
test('Costa Rica phone types enable WhatsApp for mobile 5-9 only unless explicitly marked',()=>{for(const digit of ['5','6','7','8','9']){const numero='506'+digit+'1234567';assert.equal(C.phoneType(numero),'mobile');assert.equal(C.hasWhatsApp({numero,contacto:''}),true);}for(const digit of ['2','3','4']){const numero='506'+digit+'1234567';assert.equal(C.phoneType(numero),'fixed');assert.equal(C.hasWhatsApp({numero,contacto:''}),false);}assert.equal(C.hasWhatsApp({numero:'50641234567',contacto:'WHATSAPP EMPRESA'}),true);assert.equal(C.phoneType('50767815279'),'international');});
test('La Gamba resolves to Golfito and suggests its logistics corridor',()=>{const place=C.resolvePlace(' La Gámba ',localities,homonyms,cantons);assert.equal(place.type,'locality');assert.equal(place.canton,'Golfito');assert.equal(place.province,'Puntarenas');for(const center of ['GOLFITO','RÍO CLARO','PASO CANOAS'])assert.ok(place.logistics.includes(center));const rows=[{id:'G',destinos:['GOLFITO']},{id:'R',destinos:['RIO CLARO']},{id:'N',destinos:['CIUDAD NEILY']},{id:'L',destinos:['LIBERIA']}];assert.deepEqual(C.searchNearby(rows,place.logistics).map(t=>t.id),['G','R','N']);});
test('official homonyms must be disambiguated before returning carriers',()=>{const place=C.resolvePlace('Playa Hermosa',localities,homonyms,cantons);assert.equal(place.type,'ambiguous');assert.equal(place.locations.length,4);assert.deepEqual(place.locations.map(x=>x.canton),['Carrillo','Garabito','Osa','Puntarenas']);});
test('unknown names receive bounded lexical destination suggestions',()=>{const rows=[{destinos:['GOLFITO','LIBERIA']},{destinos:['RÍO CLARO']}];assert.equal(C.lexicalDestinations(rows,'GOLFTO',2)[0],'GOLFITO');assert.equal(C.lexicalDestinations(rows,'GOLFTO',2).length,2);});
