const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
function fixture(){return {schemaVersion:1,generatedAt:'2026-09-11T00:00:00Z',transportistas:[{id:'A',nombre:'<img src=x onerror=alert(1)>',horario:'L-V',imagen:'javascript:alert(1)',destinos:['LIBERIA'],telefonos:[{numero:'50671529650',contacto:'WHATSAPP'},{numero:'50651234567',contacto:'VENTAS'},{numero:'50641234567',contacto:'OFICINA'}],bodegas:[{id:'D1',direccion:'LOCAL <script>evil()</script>',zona:'TIBÁS',lat:10,lng:-84},{id:'D2',direccion:'PENDIENTE',zona:'SAN CARLOS',lat:null,lng:null}]}]};}
const reference={localities:{'la gamba':['Golfito','Puntarenas','Guaycará']},cantons:{Golfito:{cabecera:'GOLFITO',provincia:'Puntarenas',centrosCercanos:['GOLFITO','RÍO CLARO','CIUDAD NEILY','PASO CANOAS']},Acosta:{cabecera:'SAN IGNACIO',provincia:'San José',centrosCercanos:['ACOSTA','SAN IGNACIO']}},homonyms:{'playa hermosa':[['Carrillo','Guanacaste'],['Garabito','Puntarenas']],'acosta':[['Acosta','San José'],['Alajuela','Alajuela']]}};
async function setup(fetcher){const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://example.test/directorio-transportistas-/',runScripts:'outside-only'});const w=dom.window,dataFetch=fetcher|| (async()=>({ok:true,json:async()=>fixture()}));w.fetch=async u=>{const url=String(u);if(url.includes('/assets/carriers/manifest.json'))return {ok:true,json:async()=>({schemaVersion:1,images:{}})};if(url.includes('/assets/localidades_dta_cr.json'))return {ok:true,json:async()=>reference.localities};if(url.includes('/assets/cantones_logistica_cr.json'))return {ok:true,json:async()=>reference.cantons};if(url.includes('/assets/homonimos_dta_cr.json'))return {ok:true,json:async()=>reference.homonyms};return dataFetch(u);};w.AbortController=AbortController;w.matchMedia=()=>({matches:false});w.eval(fs.readFileSync('assets/js/core.js','utf8'));w.eval(fs.readFileSync('assets/js/app.js','utf8'));await new Promise(r=>setTimeout(r,15));return dom;}
test('search safely renders payload, circular fallback and icon actions',async()=>{const d=await setup();try{const w=d.window,doc=w.document;assert.equal(doc.querySelector('#buscar').disabled,false);const q=doc.querySelector('#consulta');q.value='libéria';q.dispatchEvent(new w.Event('input'));doc.querySelector('#busqueda').dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,15));assert.equal(doc.querySelectorAll('article').length,1);assert.equal(doc.querySelector('article h3').textContent.toLowerCase(),'<img src=x onerror=alert(1)>');assert.equal(doc.querySelectorAll('article script').length,0);assert.ok(doc.querySelector('.avatar-iniciales'));assert.equal(doc.querySelectorAll('a[href*="destination="]').length,1);assert.equal(doc.querySelectorAll('.bodega-item').length,2);assert.equal(doc.querySelectorAll('.icono-boton.waze,.icono-boton.maps').length,2);assert.equal(doc.querySelectorAll('.chip').length,1);assert.equal(doc.querySelectorAll('.accion-contacto.whatsapp').length,2);assert.equal(doc.querySelectorAll('.accion-contacto.llamada').length,3);assert.equal(doc.querySelector('a[href="https://wa.me/50651234567"] span'),null);assert.equal(doc.querySelector('a[href="https://wa.me/50651234567"]').getAttribute('aria-label'),'Enviar WhatsApp al +506 5123-4567');assert.equal(doc.querySelector('a[href="tel:+50641234567"] span').textContent,'Llamar');doc.querySelector('#limpiar').click();assert.equal(q.value,'');assert.equal(doc.querySelectorAll('article').length,0);}finally{d.window.close();}});
test('La Gamba renders clearly labeled carriers serving nearby Golfito logistics centers',async()=>{const source=fixture();source.transportistas.push({id:'B',nombre:'Ruta Sur',horario:'',imagen:'',destinos:['GOLFITO','RÍO CLARO'],telefonos:[],bodegas:[]},{id:'C',nombre:'Frontera',horario:'',imagen:'',destinos:['PASO CANOAS'],telefonos:[],bodegas:[]});const d=await setup(async()=>({ok:true,json:async()=>source}));try{const w=d.window,doc=w.document;doc.querySelector('#consulta').value='La Gamba';doc.querySelector('#busqueda').dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,20));assert.match(doc.querySelector('.territorial-aviso').textContent,/no hay servicio confirmado/i);assert.match(doc.querySelector('.territorial-aviso').textContent,/Guaycará/i);assert.equal(doc.querySelectorAll('article').length,2);assert.equal(doc.querySelectorAll('.cobertura-badge').length,2);assert.match(doc.querySelector('#tituloResultados').textContent,/viajan por el área/i);}finally{d.window.close();}});
test('clearing a pending territorial search restores controls',async()=>{const d=await setup();try{const w=d.window,doc=w.document,q=doc.querySelector('#consulta');q.value='La Gamba';doc.querySelector('#busqueda').dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal(doc.querySelector('#buscar').disabled,true);doc.querySelector('#limpiar').click();assert.equal(doc.querySelector('#buscar').disabled,false);assert.equal(doc.querySelector('#resultados').hasAttribute('aria-busy'),false);await new Promise(r=>setTimeout(r,10));assert.equal(doc.querySelectorAll('article').length,0);}finally{d.window.close();}});
test('homonymous destinations require a canton choice and do not mix carriers',async()=>{const d=await setup();try{const w=d.window,doc=w.document;doc.querySelector('#consulta').value='Playa Hermosa';doc.querySelector('#busqueda').dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,20));assert.equal(doc.querySelectorAll('article').length,0);assert.equal(doc.querySelectorAll('.territorial-opcion').length,2);assert.match(doc.querySelector('#tituloResultados').textContent,/precisar/i);}finally{d.window.close();}});
test('Acosta selection returns only exact Acosta assignments, never province-wide San José routes',async()=>{const source=fixture();source.transportistas.push({id:'ACO',nombre:'Ruta Acosta',horario:'',imagen:'',destinos:['ACOSTA'],telefonos:[],bodegas:[]},{id:'SJ',nombre:'Ruta San José',horario:'',imagen:'',destinos:['SAN JOSÉ'],telefonos:[],bodegas:[]});const d=await setup(async()=>({ok:true,json:async()=>source}));try{const w=d.window,doc=w.document;doc.querySelector('#consulta').value='Acosta';doc.querySelector('#busqueda').dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,20));const buttons=doc.querySelectorAll('.territorial-opcion');assert.equal(buttons.length,2);buttons[0].click();assert.equal(doc.querySelectorAll('article').length,1);assert.equal(doc.querySelector('article h3').textContent,'Ruta Acosta');assert.doesNotMatch(doc.querySelector('#tarjetas').textContent,/Ruta San José/);assert.match(doc.querySelector('.territorial-aviso').textContent,/exactamente a Acosta/i);}finally{d.window.close();}});
test('failed load has retry; recovery does not duplicate handlers',async()=>{let count=0;const d=await setup(async()=>++count===1?{ok:false,status:503}:{ok:true,json:async()=>fixture()});try{const doc=d.window.document;assert.equal(doc.querySelector('#reintentar').hidden,false);assert.equal(doc.querySelector('#buscar').disabled,true);doc.querySelector('#reintentar').click();await new Promise(r=>setTimeout(r,15));assert.equal(doc.querySelector('#buscar').disabled,false);assert.equal(count,2);}finally{d.window.close();}});
test('directory uses relative repository JSON and map is not loaded during search',async()=>{let url;const d=await setup(async u=>{url=String(u);return {ok:true,json:async()=>fixture()};});try{assert.equal(url,'https://example.test/directorio-transportistas-/data/transportistas.json');assert.equal(d.window.document.querySelectorAll('script[src*="leaflet"]').length,0);assert.equal(d.window.document.querySelector('#panelMapa').hidden,true);}finally{d.window.close();}});
test('source has iOS padding, circular cover images and no inline handlers',()=>{const css=fs.readFileSync('assets/css/app.css','utf8'),html=fs.readFileSync('index.html','utf8');assert.match(css,/padding:13px 58px 13px 14px/);assert.match(css,/-webkit-appearance:none/);assert.match(css,/border-radius:50%;object-fit:cover;aspect-ratio:1\/1/);assert.equal(JSON.parse(fs.readFileSync('manifest.json')).orientation,'any');assert.doesNotMatch(html,/\son(?:click|error|change)=/i);});
test('versioned shell assets prevent stale UX after deployment',()=>{const html=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8');for(const asset of ['app.css','core.js','app.js']){assert.match(html,new RegExp(asset.replace('.','\\.')+'\\?v=28'));assert.match(sw,new RegExp(asset.replace('.','\\.')+'\\?v=28'));}assert.match(sw,/rutas-cr-shell-v28/);});
test('map contract disables hover zoom, resets after leave and clusters distinct companies',async()=>{
 const d=await setup();try{
  const w=d.window,doc=w.document,events={},state={handlers:{},pins:[]};
  const m={setView(){return this;},on(name,fn){events[name]=fn;return this;},addLayer(){},fitBounds(){},invalidateSize(){},removeLayer(){}};
  for(const name of ['scrollWheelZoom','dragging','touchZoom','doubleClickZoom','boxZoom','keyboard'])m[name]={enable(){state.handlers[name]=true;},disable(){state.handlers[name]=false;}};
  w.L={map(id,opts){state.opts=opts;return m;},tileLayer(){return {addTo(){return this;},on(){return this;}};},markerClusterGroup(opts){state.clusterOpts=opts;return {clearLayers(){state.pins=[];},addLayers(pins){state.pins=pins;},getBounds(){return {};}};},marker(coords,options){return {options,bindPopup(){return this;}};},divIcon:o=>o,point:(x,y)=>({x,y})};
  doc.querySelector('#consulta').value='LIBERIA';doc.querySelector('#busqueda').dispatchEvent(new w.Event('submit',{cancelable:true}));doc.querySelector('#mostrarMapa').click();await new Promise(r=>setTimeout(r,10));
  assert.equal(state.opts.scrollWheelZoom,false);assert.equal(state.opts.dragging,false);assert.equal(state.pins.length,1);assert.equal(state.clusterOpts.spiderfyOnMaxZoom,true);assert.equal(state.clusterOpts.zoomToBoundsOnClick,true);
  assert.equal(state.clusterOpts.iconCreateFunction({getAllChildMarkers:()=>[{options:{carrierId:'A'}},{options:{carrierId:'A'}},{options:{carrierId:'B'}}]}).html,'2');
  events.click();assert.equal(state.handlers.scrollWheelZoom,true);doc.querySelector('#mapa').dispatchEvent(new w.Event('mouseleave'));assert.equal(state.handlers.scrollWheelZoom,false);
  doc.querySelector('#activarMapa').click();assert.equal(state.handlers.dragging,true);w.dispatchEvent(new w.Event('blur'));assert.equal(state.handlers.dragging,false);
 }finally{d.window.close();}
});
