const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
function fixture(){return {schemaVersion:1,generatedAt:'2026-09-11T00:00:00Z',transportistas:[{id:'A',nombre:'<img src=x onerror=alert(1)>',horario:'L-V',imagen:'javascript:alert(1)',destinos:['LIBERIA'],telefonos:[{numero:'50671529650',contacto:'WHATSAPP'}],bodegas:[{id:'D1',direccion:'LOCAL <script>evil()</script>',zona:'TIBÁS',lat:10,lng:-84},{id:'D2',direccion:'PENDIENTE',zona:'SAN CARLOS',lat:null,lng:null}]}]};}
async function setup(fetcher){const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://example.test/directorio-transportistas-/',runScripts:'outside-only'});const w=dom.window;w.fetch=fetcher|| (async()=>({ok:true,json:async()=>fixture()}));w.AbortController=AbortController;w.matchMedia=()=>({matches:false});w.eval(fs.readFileSync('assets/js/core.js','utf8'));w.eval(fs.readFileSync('assets/js/app.js','utf8'));await new Promise(r=>setTimeout(r,15));return dom;}
test('search form safely renders payload, clear restores state, missing GPS never navigates',async()=>{const d=await setup();try{const w=d.window,doc=w.document;assert.equal(doc.querySelector('#buscar').disabled,false);const q=doc.querySelector('#consulta');q.value='libéria';q.dispatchEvent(new w.Event('input'));assert.equal(doc.querySelector('#limpiar').hidden,false);doc.querySelector('#busqueda').dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal(doc.querySelectorAll('article').length,1);assert.equal(doc.querySelector('article h3').textContent,'<img src=x onerror=alert(1)>');assert.equal(doc.querySelectorAll('article script, article img').length,0);assert.equal(doc.querySelectorAll('a[href*="destination="]').length,1);assert.equal(doc.querySelectorAll('.bodega-item').length,2);doc.querySelector('#limpiar').click();assert.equal(q.value,'');assert.equal(doc.querySelectorAll('article').length,0);}finally{d.window.close();}});
test('failed load has retry; recovery does not duplicate handlers',async()=>{let count=0;const d=await setup(async()=>++count===1?{ok:false,status:503}:{ok:true,json:async()=>fixture()});try{const doc=d.window.document;assert.equal(doc.querySelector('#reintentar').hidden,false);assert.equal(doc.querySelector('#buscar').disabled,true);doc.querySelector('#reintentar').click();await new Promise(r=>setTimeout(r,15));assert.equal(doc.querySelector('#buscar').disabled,false);assert.equal(count,2);}finally{d.window.close();}});
test('directory uses relative repository JSON and map is not loaded during search',async()=>{let url;const d=await setup(async u=>{url=String(u);return {ok:true,json:async()=>fixture()};});try{assert.equal(url,'https://example.test/directorio-transportistas-/data/transportistas.json');assert.equal(d.window.document.querySelectorAll('script[src*="leaflet"]').length,0);assert.equal(d.window.document.querySelector('#panelMapa').hidden,true);}finally{d.window.close();}});
test('source has iOS padding, no orientation lock, no inline event handlers',()=>{const css=fs.readFileSync('assets/css/app.css','utf8'),html=fs.readFileSync('index.html','utf8');assert.match(css,/padding:13px 58px 13px 12px !important/);assert.match(css,/-webkit-appearance:none/);assert.equal(JSON.parse(fs.readFileSync('manifest.json')).orientation,'any');assert.doesNotMatch(html,/\son(?:click|error|change)=/i);});
test('map contract disables hover zoom, resets after leave and clusters distinct companies',async()=>{
 const d=await setup();try{
  const w=d.window,doc=w.document,events={},state={handlers:{},pins:[]};
  const m={setView(){return this;},on(name,fn){events[name]=fn;return this;},addLayer(){},fitBounds(){},invalidateSize(){},removeLayer(){}};
  for(const name of ['scrollWheelZoom','dragging','touchZoom','doubleClickZoom','boxZoom','keyboard'])m[name]={enable(){state.handlers[name]=true;},disable(){state.handlers[name]=false;}};
  w.L={map(id,opts){state.opts=opts;return m;},tileLayer(){return {addTo(){return this;},on(){return this;}};},markerClusterGroup(opts){state.clusterOpts=opts;return {clearLayers(){state.pins=[];},addLayers(pins){state.pins=pins;},getBounds(){return {};}};},marker(coords,options){return {options,bindPopup(){return this;}};},divIcon:o=>o,point:(x,y)=>({x,y})};
  doc.querySelector('#consulta').value='LIBERIA';doc.querySelector('#busqueda').dispatchEvent(new w.Event('submit',{cancelable:true}));doc.querySelector('#mostrarMapa').click();await new Promise(r=>setTimeout(r,10));
  assert.equal(state.opts.scrollWheelZoom,false);assert.equal(state.opts.dragging,false);assert.equal(state.pins.length,1);assert.equal(state.clusterOpts.spiderfyOnMaxZoom,true);assert.equal(state.clusterOpts.zoomToBoundsOnClick,true);
  assert.equal(state.clusterOpts.iconCreateFunction({getAllChildMarkers:()=>[{options:{carrierId:'A'}},{options:{carrierId:'A'}},{options:{carrierId:'B'}}]}).html,'2');
  events.click();assert.equal(state.handlers.scrollWheelZoom,true);doc.querySelector('#mapa').dispatchEvent(new w.Event('mouseleave'));assert.equal(state.handlers.scrollWheelZoom,false);
  doc.querySelector('#activarMapa').click();assert.equal(state.handlers.dragging,true);w.dispatchEvent(new w.Event('blur'));assert.equal(state.handlers.dragging,false);
 }finally{d.window.close();}
});
