const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),crypto=require('node:crypto');
function setup(){
 const source={TRANSPORTISTA:[['IDTRANSPORTE','TRANSPORTE','HORARIO'],['A','PRUEBA','L-V']],LUGARES:[['IDLUGARES','LUGAR'],['L','LIBERIA']],VISITA:[['IDVISITA','IDTRANSPORTE','IDLUGARES'],['V','A','L']],DIRECCION:[['IDDDIREECION','IDTRANSPORTE','DIRECCION','GPS','ZONA'],['D','A','LOCAL','10,-84','TIBÁS']],TELEFONOS:[['IDTELEFONO','IDTRANSPORTE','TELEFONO','CONTACTO'],['T','A','71529650','WHATSAPP']]};
 const props={RUTAS_SHEET_ID:'S',RUTAS_GITHUB_OWNER:'owner',RUTAS_GITHUB_REPO:'repo',RUTAS_GITHUB_BRANCH:'staging',RUTAS_GITHUB_PAT:'test-secret',RUTAS_SYNC_ENABLED:'true',RUTAS_PUBLIC_DATA_APPROVED:'true'},calls=[];
 let now=100000,remote=null,fail=0,released=0;
 const FakeDate=class extends Date {constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}};
 const blob=value=>({getBytes:()=>Array.from(Buffer.isBuffer(value)?value:Buffer.from(value)),getDataAsString:()=>Buffer.from(value).toString('utf8')});
 const context=vm.createContext({Date:FakeDate,console:{log(){},error(){}},Utilities:{sleep(){},newBlob:blob,base64Decode:s=>Buffer.from(s,'base64'),base64Encode:b=>Buffer.from(b).toString('base64'),DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(alg,value)=>Array.from(crypto.createHash('sha256').update(value).digest())},
 PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k]??null,setProperty:(k,v)=>props[k]=v,setProperties:o=>Object.assign(props,o),deleteProperty:k=>delete props[k]})},
 SpreadsheetApp:{openById:()=>({getSheetByName:name=>({getDataRange:()=>({getDisplayValues:()=>source[name]})})})},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){released++;}})},
 UrlFetchApp:{fetch(url,opt){calls.push({url,opt});let status=200,body={};if(url.includes('/branches/'))body={name:'staging'};else if(opt.method==='get'){if(remote)body={sha:'sha-old',encoding:'base64',content:Buffer.from(JSON.stringify(remote)).toString('base64')};else status=404;}else if(fail){status=fail;fail=0;}else{remote=JSON.parse(Buffer.from(JSON.parse(opt.payload).content,'base64').toString());status=201;body={commit:{sha:'sha-new'}};}return {getResponseCode:()=>status,getContentText:()=>JSON.stringify(body)};}}
 });vm.runInContext(fs.readFileSync('apps_script/RutasCR_Data.js','utf8'),context);vm.runInContext(fs.readFileSync('apps_script/RutasCR_Sync.gs','utf8'),context);
 return {context,props,calls,source,advance:()=>now+=300001,remote:()=>remote,setRemote:v=>remote=v,fail:v=>fail=v,released:()=>released};
}
function settle(s){assert.equal(s.context.rutasCRSincronizar().state,'settling');s.advance();}
test('disabled mode makes no network calls; no credentials printed; lock released',()=>{const s=setup();s.props.RUTAS_SYNC_ENABLED='false';assert.equal(s.context.rutasCRSincronizar().state,'disabled');assert.equal(s.calls.length,0);assert.equal(s.released(),1);});
test('safe setup keeps synchronization and publication approval disabled',()=>{const s=setup();const result=s.context.rutasCRPrepararConfiguracion();assert.equal(result.state,'prepared');assert.equal(s.props.RUTAS_SYNC_ENABLED,'false');assert.equal(s.props.RUTAS_PUBLIC_DATA_APPROVED,'false');assert.equal(s.props.RUTAS_GITHUB_BRANCH,'fix/rutas-cr-integracion-segura');});
test('diagnostic only requires the Sheet ID and never calls GitHub',()=>{const s=setup();delete s.props.RUTAS_GITHUB_OWNER;delete s.props.RUTAS_GITHUB_REPO;delete s.props.RUTAS_GITHUB_BRANCH;delete s.props.RUTAS_GITHUB_PAT;const result=s.context.rutasCRDiagnosticar();assert.equal(result.transportistas,1);assert.equal(s.calls.length,0);});
test('GitHub connection test is read-only and keeps synchronization disabled',()=>{const s=setup();s.props.RUTAS_SYNC_ENABLED='false';const result=s.context.rutasCRProbarGitHub();assert.equal(result.state,'connected');assert.equal(result.syncEnabled,false);assert.equal(s.calls.length,1);assert.equal(s.calls[0].opt.method,'get');});
test('two stable runs create UTF8 snapshot; unchanged snapshot does not commit',()=>{const s=setup();settle(s);assert.equal(s.context.rutasCRSincronizar().state,'updated');assert.equal(s.remote().transportistas[0].bodegas[0].zona,'TIBÁS');assert.equal(s.context.rutasCRSincronizar().state,'unchanged');assert.equal(s.calls.filter(c=>c.opt.method==='put').length,1);assert.equal(s.props.RUTAS_LAST_COMMIT,'sha-new');});
test('SHA included on update; HTTP 409 refetches and retries',()=>{const s=setup();settle(s);s.context.rutasCRSincronizar();s.source.TRANSPORTISTA[1][2]='L-S';settle(s);s.fail(409);assert.equal(s.context.rutasCRSincronizar().state,'updated');const puts=s.calls.filter(c=>c.opt.method==='put');assert.equal(puts.length,3);assert.equal(JSON.parse(puts.at(-1).opt.payload).sha,'sha-old');});
test('HTTP auth failure is recorded and not called success',()=>{const s=setup();settle(s);s.fail(403);assert.throws(()=>s.context.rutasCRSincronizar(),/403/);assert.ok(s.props.RUTAS_LAST_ERROR);assert.equal(s.props.RUTAS_LAST_OK,undefined);});
test('destination removal requires approval for that exact hash',()=>{const s=setup();settle(s);s.context.rutasCRSincronizar();s.source.VISITA.splice(1);settle(s);assert.throws(()=>s.context.rutasCRSincronizar(),/Reducción/);s.props.RUTAS_APPROVED_DELETION_HASH=s.context.rutasCRDiagnosticar().hash;assert.equal(s.context.rutasCRSincronizar().state,'updated');assert.equal(s.props.RUTAS_APPROVED_DELETION_HASH,undefined);});
test('bad FK aborts without replacing remote',()=>{const s=setup();settle(s);s.context.rutasCRSincronizar();const old=JSON.stringify(s.remote());s.source.VISITA[1][2]='MISSING';assert.throws(()=>s.context.rutasCRSincronizar(),/huérfana/);assert.equal(JSON.stringify(s.remote()),old);});
test('duplicate visit is reported but does not block a deduplicated public snapshot',()=>{const s=setup();s.source.VISITA.push(['V2','A','L']);const diagnostic=s.context.rutasCRDiagnosticar();assert.ok(diagnostic.diagnostics.some(d=>d.code==='DUPLICATE_VISIT'));settle(s);assert.equal(s.context.rutasCRSincronizar().state,'updated');assert.deepEqual(Array.from(s.remote().transportistas[0].destinos),['LIBERIA']);});
